In [1]:
import torch
import torch.nn as nn
import torchvision 

In [2]:
torch.cuda.is_available()
torch.__version__

'2.4.1+cu124'

In [3]:
scalar=torch.tensor(10)
scalar.ndim# tensorun boyutunu aldık

0

In [4]:
scalar.item()# tensorun içindeki sayıyı aldık.

10

In [5]:
vector=torch.tensor([[7,7],[1,3]])
vector.shape

torch.Size([2, 2])

In [6]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])# 1 matrix 3 row 3 col
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [7]:
print(tensor.ndim,tensor.shape)

3 torch.Size([1, 3, 3])


In [8]:
tensor.size()

torch.Size([1, 3, 3])

In [9]:
random_tensor=torch.rand(size=(3,4))
random_tensor

tensor([[0.9906, 0.8512, 0.4168, 0.9260],
        [0.1887, 0.8101, 0.2496, 0.4723],
        [0.9678, 0.6245, 0.5146, 0.3496]])

In [10]:
random_tensor=torch.rand(size=(2,100,50))
random_tensor

tensor([[[0.6232, 0.6690, 0.7641,  ..., 0.5284, 0.8210, 0.0459],
         [0.0860, 0.8504, 0.1142,  ..., 0.0617, 0.7199, 0.1115],
         [0.7247, 0.3592, 0.8346,  ..., 0.8238, 0.4205, 0.3652],
         ...,
         [0.4206, 0.7345, 0.6121,  ..., 0.3595, 0.7190, 0.6382],
         [0.1024, 0.3688, 0.2290,  ..., 0.6644, 0.7201, 0.0443],
         [0.2475, 0.4749, 0.5813,  ..., 0.1835, 0.9851, 0.0513]],

        [[0.8124, 0.6366, 0.9117,  ..., 0.7463, 0.0964, 0.5321],
         [0.6787, 0.0309, 0.8575,  ..., 0.3339, 0.7701, 0.3707],
         [0.8279, 0.6798, 0.6819,  ..., 0.2176, 0.8055, 0.2670],
         ...,
         [0.0653, 0.2386, 0.3745,  ..., 0.4405, 0.3485, 0.0741],
         [0.2775, 0.4299, 0.0527,  ..., 0.8195, 0.9138, 0.0110],
         [0.6400, 0.6318, 0.4648,  ..., 0.4608, 0.4717, 0.5144]]])

In [11]:
zeros=torch.zeros(1,2)
zeros

tensor([[0., 0.]])

In [12]:
ones_tensor=torch.ones(1,2)
ones_tensor

tensor([[1., 1.]])

In [13]:
range_tensor=torch.range(start=0,end=10,step=2)
range_tensor.dtype

/tmp/ipykernel_40092/3966293940.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor=torch.range(start=0,end=10,step=2)


torch.float32

In [14]:
arange_tensor=torch.arange(0,10,step=2)
arange_tensor.dtype

torch.int64

In [15]:
ten_zeros=torch.full_like(range_tensor,fill_value=5,dtype=torch.bool)# varolan bir tensor ile aynı boyuta sahip yeni bir matris oluşturmak için kullanılır.
ten_zeros

tensor([True, True, True, True, True, True])

In [16]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device="cuda", # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [17]:
# Create a tensor
some_tensor = torch.rand(1,3, 4,device="cuda")

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[[0.5895, 0.8973, 0.7044, 0.2941],
         [0.7443, 0.1107, 0.9789, 0.9593],
         [0.5856, 0.1037, 0.2001, 0.2474]]], device='cuda:0')
Shape of tensor: torch.Size([1, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


### Tensor Operations

In [18]:
tensor=torch.randint(low=0,high=100,size=(5,5))# defaul low=0
tensor

tensor([[46, 43, 52, 54, 76],
        [65, 36,  2,  0, 14],
        [69, 73, 32, 10, 33],
        [99, 64, 49, 88, 50],
        [41, 69, 40, 24, 87]])

In [19]:
tensor2=torch.randint(size=(5,5),high=10)
tensor2

tensor([[4, 2, 5, 7, 4],
        [2, 5, 8, 5, 2],
        [5, 1, 3, 3, 9],
        [8, 3, 6, 0, 8],
        [0, 5, 7, 7, 2]])

In [20]:
tensor3=tensor+tensor2

In [21]:
tensor3/2

tensor([[25.0000, 22.5000, 28.5000, 30.5000, 40.0000],
        [33.5000, 20.5000,  5.0000,  2.5000,  8.0000],
        [37.0000, 37.0000, 17.5000,  6.5000, 21.0000],
        [53.5000, 33.5000, 27.5000, 44.0000, 29.0000],
        [20.5000, 37.0000, 23.5000, 15.5000, 44.5000]])

In [22]:
tensor3

tensor([[ 50,  45,  57,  61,  80],
        [ 67,  41,  10,   5,  16],
        [ 74,  74,  35,  13,  42],
        [107,  67,  55,  88,  58],
        [ 41,  74,  47,  31,  89]])

In [23]:
torch.multiply(tensor3,10)

tensor([[ 500,  450,  570,  610,  800],
        [ 670,  410,  100,   50,  160],
        [ 740,  740,  350,  130,  420],
        [1070,  670,  550,  880,  580],
        [ 410,  740,  470,  310,  890]])

In [24]:
tensor3

tensor([[ 50,  45,  57,  61,  80],
        [ 67,  41,  10,   5,  16],
        [ 74,  74,  35,  13,  42],
        [107,  67,  55,  88,  58],
        [ 41,  74,  47,  31,  89]])

In [25]:
filter=torch.randint(size=(5,5),high=2)
tensor3=torch.randint(size=(5,5),high=10)
tensor3

tensor([[1, 6, 4, 9, 4],
        [9, 9, 5, 3, 1],
        [2, 6, 3, 8, 5],
        [4, 2, 8, 7, 1],
        [3, 7, 5, 9, 8]])

In [26]:
filter

tensor([[0, 0, 0, 0, 1],
        [1, 1, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [0, 0, 1, 0, 0]])

In [27]:
matmul_tensor=torch.matmul(tensor3,filter) # matris bazında çarpım
matmul_tensor

tensor([[15, 19,  8, 13, 20],
        [12, 17,  6,  8, 26],
        [14, 17,  8, 11, 19],
        [ 9, 17,  9, 15, 21],
        [16, 21, 13, 14, 24]])

In [28]:
matmul_tensor.T# transpozu alındı

tensor([[15, 12, 14,  9, 16],
        [19, 17, 17, 17, 21],
        [ 8,  6,  8,  9, 13],
        [13,  8, 11, 15, 14],
        [20, 26, 19, 21, 24]])

In [29]:
linear=nn.Linear(in_features=3,out_features=6)

In [30]:
x=torch.rand(size=(2,3))

In [31]:
output=linear(x)

In [32]:
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output:
tensor([[-0.2628, -0.4171,  0.0312,  0.5713,  0.7507, -0.0536],
        [-0.4393, -0.2115,  0.2193,  0.9606,  0.8629, -0.2139]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


In [33]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0.234516441822052
Maximum: 0.8070580363273621
Mean: 0.499153733253479
Sum: 2.994922399520874


In [34]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0.8071), tensor(0.2345), tensor(0.4992), tensor(2.9949))

In [35]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [36]:
tensor=torch.zeros(size=(1,2,2))
tensor=tensor.squeeze()# gereksiz 11 boyutlu olanları kaldırır.
tensor.shape

torch.Size([2, 2])

In [37]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [38]:
x=x.squeeze()

In [39]:
x[1][1]

tensor(5)

In [40]:
x.shape

torch.Size([3, 3])

In [41]:
# Count number of devices
torch.cuda.device_count()

1

### Running Tensor on GPU

In [42]:
device="cuda"
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')